apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.app.url }}
spec:
  commonName: {{ .Values.app.url }}
  dnsNames:
    - {{ .Values.app.url }}
  secretName: {{ .Values.app.url }}
  issuerRef:
    name: {{ .Values.app.url }}
    kind: Issuer