apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.app.url }}
spec:
  dnsNames:
    - {{ .Values.app.url }}
  secretName: {{ .Values.app.url }}
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer