{{ if .Values.iam.service_account_name }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.iam.service_account_name }}
  annotations:
    {{ if .Values.iam.service_account_role }}
    eks.amazonaws.com/role-arn: {{ .Values.iam.service_account_role }}
    {{ end }}
{{ end }}